my_flask_blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Название', validators=[DataRequired()])
    content = TextAreaField('Текст', validators=[DataRequired()])
    submit = SubmitField('Создать')


class CommentForm(FlaskForm):
    comment = StringField('Комментарий', validators=[DataRequired()])

my_flask_blog/main/routes.py
from flask import render_template, Blueprint
from my_flask_blog.models import User

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    return render_template('index.html')

my_flask_blog/posts/routes.py
from flask import (render_template, url_for, flash, redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from my_flask_blog import db
from my_flask_blog.models import Post, Comment
from my_flask_blog.posts.forms import PostForm, CommentForm

posts = Blueprint('posts', __name__)


@posts.route("/allpost")
@login_required
def allpost():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('allpost.html', posts=posts)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, user_id=current_user.id)
        db.session.add(post)
        db.session.commit()
        flash('Ваш пост создан!', 'success')
        return redirect(url_for('posts.allpost'))
    return render_template('create_post.html', title='Новый пост', form=form, legend='Новый пост')


@posts.route("/post/<int:post_id>", methods=['GET', 'POST'])
def post(post_id):
    post = Post.query.get_or_404(post_id)
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(body=form.comment.data, post_id=post_id, username=current_user.username)
        db.session.add(comment)
        db.session.commit()
        flash('Ваш комментарий добавлен!', 'success')
        return redirect(f'/post/{post_id}')
    return render_template('post.html', title=post.title, post=post, form=form)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Ваш пост обновлен!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Обновление поста', form=form, post=post, legend='Обновление поста')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    if post.comments:
        for comment in post.comments:
            db.session.delete(comment)
            db.session.commit()
    db.session.delete(post)
    db.session.commit()
    flash('Ваш пост был удален!', 'success')
    return redirect(url_for('posts.allpost'))


@posts.route("/comment/<int:comment_id>/delete", methods=['POST'])
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if comment.username != current_user.username:
        abort(403)
    db.session.delete(comment)
    db.session.commit()
    flash('Ваш комментарий был удален!', 'success')
    redirect_path = request.referrer[-7:]
    return redirect(redirect_path)

my_flask_blog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, abort, current_app
from flask_login import login_user, current_user, logout_user, login_required

from my_flask_blog import db, bcrypt
from my_flask_blog.models import User, Post
from my_flask_blog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from my_flask_blog.users.utils import save_picture
from my_flask_blog.users.utils import send_reset_email


users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Ваша учетная запись была создана! Теперь вы можете войти в систему', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Регистрация', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            return redirect(url_for('posts.allpost'))
        else:
            flash('Войти не удалось. Пожалуйста, проверьте электронную почту и пароль', 'внимание')
    return render_template('login.html', title='Аутентификация', form=form)


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Ваш аккаунт был обновлен!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        page = request.args.get('page', 1, type=int)
        user = User.query.filter_by(username=form.username.data).first_or_404()
        posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form, posts=posts, user=user)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allposts'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('На почту отправлено письмо с инструкциями по сбросу пароля.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Сброс пароля', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Это недействительный или просроченный токен', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Ваш пароль был обновлен! Теперь вы можете авторизоваться.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Сброс пароля', form=form)

my_flask_blog/templates/account.html
{% extends "base.html" %}

{% block content %}


      <div class="media">
          <img src="{{ image_file }}">
          <h2>{{ current_user.username }}</h2>
          <p>{{ current_user.email }}</p>
      </div>

        <div id="content">
        <!-- insert the page content here -->
        <h1>Аккаунт пользователя</h1>
        <form action="" method="post" enctype="multipart/form-data">
          {{ form.hidden_tag() }}
          <div class="form_settings">

            <p><span>Имя пользователя</span><input class="contact" type="text" name="username" value="{{ current_user.username }}" />
            {% if form.username.errors %}
              {% for error in form.username.errors %}
              <p style="color: red">{{ error }}</p>
              {% endfor %}
            {% endif %}
            </p>

            <p><span>Email</span><input class="contact" type="text" name="email" value="{{ current_user.email }}" />
              {% if form.email.errors %}
                  {% for error in form.email.errors %}
                  <p style="color: red">{{ error }}</p>
                  {% endfor %}
              {% endif %}
            </p>

              <p>
                  <span>{{ form.picture.label() }}</span>
                  {{ form.picture(class="form-control-file") }}
                  {% if form.picture.errors %}
                      {% for error in form.picture.errors %}
                          <span>{{ error }}</span></br>
                      {% endfor %}
                  {% endif %}
              </p>

            <p style="padding-top: 15px"><span>&nbsp;</span><input class="submit" type="submit" name="submit" value="Обновить" /></p>
          </div>
        </form>
      </div>

{% endblock %}

my_flask_blog/templates/allpost.html
{% extends "base.html" %}

{% block content %}
  {% for post in posts.items %}
  <div class="container" style="display: flex;">
    <article class="media" style="display: flex; flex-direction: column; width: 100px;">
      <img class="rounded-circle article-img" style="margin-right: 5px;" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
      <a href="{{ url_for('users.user_posts', username=post.author.username) }}" id="author" style="margin: 5px auto;">{{ post.author.username }}</a>
    </article>

    <div class="card" style="margin: 0 10px 20px;">
      <div class="card-body">
        <h4 class="card-title"><a class="title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h4>
        <small>Опубликовано {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
        <br>
        <br>
        <p class="card-text">{{ post.content[:150] }}...</p>
      </div>

    </div>
  </div>
  {% endfor %}

  {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
      {% if posts.page == page_num %}
        <a class="btn btn-success mb-4" href="{{ url_for('posts.allpost', page=page_num) }}">{{ page_num }}</a>
      {% else %}
        <a class="btn btn-outline-success mb-4" href="{{ url_for('posts.allpost', page=page_num) }}">{{ page_num }}</a>
      {% endif %}
    {% else %}
      ...
    {% endif %}
  {% endfor %}
{% endblock content %}

my_flask_blog/templates/base.html
<!DOCTYPE HTML>
<html>

<head>
    {% if title %}
        <title>Блог - {{ title }}</title>
    {% else %}
        <title>Блог</title>
    {% endif %}
  <meta name="description" content="website description" />
  <meta name="keywords" content="website keywords, website keywords" />
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style/style.css') }}" />
  {% block style %} {% endblock style %}
</head>

<body>
  <div id="main">
    <div id="header">
      <div id="logo">
        <div id="logo_text">
          <!-- class="logo_colour", allows you to change the colour of the text -->
          <h1><a href="{{ url_for('main.home') }}">Еще один<span class="logo_colour">&ensp;блог</span></a></h1>
          <h2>Написан на фреймворке Flask</h2>
        </div>
      </div>
      <div id="menubar">
        <ul id="menu">
          <!-- put class="selected" in the li tag for the selected page - to highlight which page you're on -->
          <li class="selected"><a href="{{ url_for('main.home') }}">Home</a></li>
<!--          <li><a href="examples.html">Examples</a></li>-->
<!--          <li><a href="page.html">A Page</a></li>-->
<!--          <li><a href="contact.html">Contact Us</a></li>-->
          {% if current_user.is_authenticated %}
          <li><a href="{{ url_for('posts.allpost') }}">Посты</a></li>
          <li><a href="{{ url_for('posts.new_post') }}">Создать пост</a></li>
          <li><a href="{{ url_for('users.account') }}">Профиль {{ current_user.username }}</a></li>
          <li><a href="{{ url_for('users.logout') }}">Выйти</a></li>
          {% for role in  current_user.roles%}
          {% if role == 'admin' %}
          <li><a href="{{ url_for('admin.index') }}">Админка</a></li>
          {% endif %}
          {% endfor %}

          {% else %}
          <li><a href="{{ url_for('users.login') }}">Войти</a></li>
          <li><a href="{{ url_for('users.register') }}">Зарегистрироваться</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
    <div id="content_header"></div>
    <div id="site_content">
      <div class="sidebar">
        <!-- insert your sidebar items here -->
        <h3>Latest News</h3>
        <h4>New Website Launched</h4>
        <h5>January 1st, 2011</h5>
        <p>2011 sees the redesign of our website. Take a look around and let us know what you think.<br /><a href="#">Read more</a></p>
        <p></p>
        <h4>New Website Launched</h4>
        <h5>January 1st, 2011</h5>
        <p>2011 sees the redesign of our website. Take a look around and let us know what you think.<br /><a href="#">Read more</a></p>
        <h3>Useful Links</h3>
        <ul>
          <li><a href="#">link 1</a></li>
          <li><a href="#">link 2</a></li>
          <li><a href="#">link 3</a></li>
          <li><a href="#">link 4</a></li>
        </ul>
        <h3>Search</h3>
        <form method="post" action="#" id="search_form">
          <p>
            <input class="search" type="text" name="search_field" value="Enter keywords....." />
            <input name="search" type="image" style="border: 0; margin: 0 0 -9px 5px;" src="../static/style/search.png" alt="Search" title="Search" />
          </p>
        </form>
      </div>


      <main role="main" class="container">
        <div>
<!--          <div>-->
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                  <div style="width: 500px; color: #00C5EE; padding: 15px; font-size: 20px;" class="alert alert-{{ category }}">
                    {{ message }}
                  </div>
                {% endfor %}
              {% endif %}
            {% endwith %}
<!--                </div>-->
        </div>
      </main>

            {% block content %}{% endblock %}

    </div>
    <div id="content_footer"></div>
    <div id="footer">
      <p><a href="{{ url_for('main.home') }}">Home</a></p>
    </div>
  </div>
</body>
</html>

my_flask_blog/templates/create_post.html
{% extends "base.html" %}

{% block content %}

  <div id="content">
        <!-- insert the page content here -->
        <h1>{{ legend }}</h1>
        <form action="" method="post">
          {{ form.hidden_tag() }}
          <div class="form_settings">

            <p><span>Название</span><input class="contact" type="text" name="title" value="{% if post %}{{ post.title }}{% else %} {% endif %}" />
             {% if form.title.errors %}
                {% for error in form.title.errors %}
                  <p style="color: red">{{ error }}</p>
                {% endfor %}
              {% endif %}
            </p>


            <p><span>Текст</span><textarea class="contact" name="content" rows="30">{% if post %}{{ post.content }}{% else %} {% endif %}</textarea>
              {% if form.content.errors %}
                {% for error in form.content.errors %}
                  <p style="color: red">{{ error }}</p>
                {% endfor %}
              {% endif %}
            </p>
            <p style="padding-top: 15px"><span>&nbsp;</span><input class="submit" type="submit" name="submit" value="Создать" /></p>
          </div>
        </form>
      </div>


{% endblock content %}

my_flask_blog/templates/index.html
{% extends "base.html" %}

{% block content %}
      <div id="content">
        <!-- insert the page content here -->
        <h1>Добро пожаловать в еще один Блог &#128512;</h1>
        <p>Как профессиональный блог поможет вам в карьере?</p>
        <p>Есть множество причин заняться блогом, в том числе для собственного развития и удовлетворения.</p>
        <ul>
          <li>Повысить квалификацию</li>
          <li>Получить более интересную работу</li>
          <li>Быть признанным сообществом</li>
          <li>Увеличить доход</li>
          <li>Приблизиться к финансовой независимости и счастью</li>
        </ul>
        <p>Зачем вести блог и быть публичным?</p>
        <ul>
          <li>Структурировать знания и активно учиться</li>
          <li>Научиться убеждать и стать красноречивее</li>
          <li>Экономика внимания</li>
          <li>Обратная связь и благодарности</li>
          <li>Независимость и свобода</li>
        </ul>



      </div>
{% endblock %}

my_flask_blog/templates/login.html
{% extends "base.html" %}

{% block content %}

      <div id="content">
        <!-- insert the page content here -->
        <h1>Авторизация</h1>
        <form action="" method="post">
          {{ form.hidden_tag() }}
          <div class="form_settings">

            <p><span>Email</span><input class="contact" type="text" name="email" value="" />
             {% if form.email.errors %}
                {% for error in form.email.errors %}
                  <p style="color: red">{{ error }}</p>
                {% endfor %}
              {% endif %}
            </p>


            <p><span>Пароль</span><input class="contact" type="password" name="password" value="" />
              {% if form.password.errors %}
                {% for error in form.password.errors %}
                  <p style="color: red">{{ error }}</p>
                {% endfor %}
              {% endif %}
            </p>
            <p style="padding-top: 15px"><span>&nbsp;</span><input class="submit" type="submit" name="submit" value="Войти" /></p>
          </div>
        </form>
      </div>

      <p style="font-size: 20px; font-weight: 500;"><a href="{{ url_for('users.reset_request') }}">Забыли пароль?</a>
      </p>

      <p style="font-size: 20px; font-weight: 500;">
          Нужен аккаунт? <a href="{{ url_for('users.register') }}">Зарегистрируйтесь</a>
      </p>

{% endblock %}

my_flask_blog/templates/post.html
{% extends "base.html" %}

{% block style %}
<style>
    /* свойства модального окна по умолчанию */
    .modal {
        position: fixed; /* фиксированное положение */
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        background: rgba(0,0,0,0.5); /* цвет фона */
        z-index: 1050;
        opacity: 0; /* по умолчанию модальное окно прозрачно */
        -webkit-transition: opacity 200ms ease-in;
        -moz-transition: opacity 200ms ease-in;
        transition: opacity 200ms ease-in; /* анимация перехода */
        pointer-events: none; /* элемент невидим для событий мыши */
        margin: 0;
        padding: 0;
    }
    /* при отображении модального окно */
    .modal:target {
        opacity: 1; /* делаем окно видимым */
          pointer-events: auto; /* элемент видим для событий мыши */
        overflow-y: auto; /* добавляем прокрутку по y, когда элемент не помещается на страницу */
    }
    /* ширина модального окна и его отступы от экрана */
    .modal-dialog {
        position: relative;
        width: auto;
        margin: 10px;
    }
    @media (min-width: 576px) {
      .modal-dialog {
          max-width: 500px;
          margin: 30px auto; /* для отображения модального окна по центру */
      }
    }
    /* свойства для блока, содержащего контент модального окна */
    .modal-content {
        position: relative;
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -webkit-flex-direction: column;
        -ms-flex-direction: column;
        flex-direction: column;
        background-color: #fff;
        -webkit-background-clip: padding-box;
        background-clip: padding-box;
        border: 1px solid rgba(0,0,0,.2);
        border-radius: .3rem;
        outline: 0;
    }
    @media (min-width: 768px) {
      .modal-content {
          -webkit-box-shadow: 0 5px 15px rgba(0,0,0,.5);
          box-shadow: 0 5px 15px rgba(0,0,0,.5);
      }
    }
    /* свойства для заголовка модального окна */
    .modal-header {
        display: -webkit-box;
        display: -webkit-flex;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-align: center;
        -webkit-align-items: center;
        -ms-flex-align: center;
        align-items: center;
        -webkit-box-pack: justify;
        -webkit-justify-content: space-between;
        -ms-flex-pack: justify;
        justify-content: space-between;
        padding: 15px;
        border-bottom: 1px solid #eceeef;
    }
    .modal-title {
        margin-top: 0;
        margin-bottom: 0;
        line-height: 1.5;
        font-size: 1.25rem;
        font-weight: 500;
    }
    /* свойства для кнопки "Закрыть" */
    .close {
        float: right;
        font-family: sans-serif;
        font-size: 24px;
        font-weight: 700;
        line-height: 1;
        color: #000;
        text-shadow: 0 1px 0 #fff;
        opacity: .5;
        text-decoration: none;
    }
    /* свойства для кнопки "Закрыть" при нахождении её в фокусе или наведении */
    .close:focus, .close:hover {
        color: #000;
        text-decoration: none;
        cursor: pointer;
        opacity: .75;
    }
    /* свойства для блока, содержащего основное содержимое окна */
    .modal-body {
      position: relative;
        -webkit-box-flex: 1;
        -webkit-flex: 1 1 auto;
        -ms-flex: 1 1 auto;
        flex: 1 1 auto;
        padding: 15px;
        overflow: auto;
    }
</style>
{% endblock style %}

{% block content %}
<div class="container" style="display: flex;">
  <article class="media" style="display: flex; flex-direction: column;"> 
    <img class="rounded-circle article-img" style="margin-right: 5px; width: 100px;" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}" style="margin: 5px auto">{{ post.author.username }}</a>
  </article>
  
  <div class="card" style="margin: 0 10px 20px;">
    <div class="card-body">
      <h4 class="card-title">{{ post.title }}</h4>
      <small>Опубликовано {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
      <br>
      <br>
      <p class="card-text" style="font-size: 16px;">{{ post.content }}</p>
    </div>

    <div class="card-footer" style="font-size: 20px; margin-top: 50px;">

      {% if post.author == current_user %}
        <div class="card-footer" style="font-size: 20px;">
          {% if post.author == current_user %}
          <a href="{{url_for('posts.update_post', post_id=post.id) }}">Обновить</a>&ensp;&ensp;&ensp;&ensp;&ensp;
          <a href="#openModal">Удалить</a>
          {% endif %}
        </div>
      {% endif %}
    </div>

  </div>
</div>

{% if post.author == current_user %}

  <div id="openModal" class="modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h3 class="modal-title">Удаление</h3>
          <a href="#close" title="Close" class="close">×</a>
        </div>
        <div class="modal-body" style="display: flex; justify-content: space-around; align-items: center;">
            <h5 class="modal-title">Удалить пост?</h5>
            <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
              <input class="submit" type="submit" value="Удалить">
            </form>
        </div>
       </div>
    </div>
  </div>

{% endif %}

      {% if post.comments %}
      {% if post.comments.count() > 0 %}
        <h2>Комментарии </h2>
        <p>{% for comment in post.comments | reverse %}
            <p style="font-size: 14px;">{{ comment.body }}</p>
            <p><small>Автор: {{ comment.username }}</small>
                <small>Дата: {{ comment.timestamp.strftime('%A, %d %B %Y %I:%M %p') }}</small></p>

            {% if comment.username == current_user.username %}
            <form action="{{ url_for('posts.delete_comment', comment_id=comment.id) }}" method="POST">
              <input class="submit" type="submit" value="Удалить">
            </form>
            {% endif %}
        <hr>
        {% endfor %}</p>
      {% endif %}
    {% endif %}

  <div id="content">
        <!-- insert the page content here -->
        <h2>Оставьте комментарий</h2>
        <form action="" method="post">
          {{ form.hidden_tag() }}
          <div class="form_settings">

            <p><span>Текст</span><textarea class="contact" name="comment" rows="5"></textarea>
              {% if form.comment.errors %}
                {% for error in form.comment.errors %}
                  <p style="color: red">{{ error }}</p>
                {% endfor %}
              {% endif %}
            </p>

            <p style="padding-top: 15px"><span>&nbsp;</span><input class="submit" type="submit" name="submit" value="Сохранить" /></p>
          </div>
        </form>
      </div>

{% endblock content %}

my_flask_blog/templates/reset_request.html
{% extends "base.html" %}

{% block content %}

    <div id="content">
        <!-- insert the page content here -->
        <h1>Сброс пароля</h1>
        <form action="" method="post">
          {{ form.hidden_tag() }}
          <div class="form_settings">

            <p><span>Email</span><input class="contact" type="text" name="email" value="" />
             {% if form.email.errors %}
                {% for error in form.email.errors %}
                  <p style="color: red">{{ error }}</p>
                {% endfor %}
              {% endif %}
            </p>

            <p style="padding-top: 15px"><span>&nbsp;</span><input class="submit" type="submit" name="submit" value="Изменить пароль" /></p>
          </div>
        </form>
      </div>

{% endblock content %}

my_flask_blog/templates/user_posts.html
{% extends "base.html" %}

{% block content %}
    <h1 class="mb-3">Посты опубликованы пользователем {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
    <div class="container" style="display: flex;">
      <article class="media" style="display: flex; flex-direction: column; width: 100px;">
        <img class="rounded-circle article-img" style="margin-right: 5px;" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}" style="margin: 5px auto">{{ post.author.username }}</a>
      </article>

      <div class="card" style="margin: 0 10px 20px;">
        <div class="card-body">
          <h4 class="card-title"><a class="title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h4>

          <small>Опубликовано {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small>
          <br>
          <br>
          <p class="card-text">{{ post.content[:150] }}...</p>
        </div>
      </div>
    </div>
    {% endfor %}


    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-success mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-success mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}